---
name: bbm conf check

on:
  push:
    paths:
      - ".github/workflows/bbm_check_conf.yml"
      - "autogen/**"
      - "builtbot.tac"
      - "common_factories.py"
      - "constants.py"
      - "locks.py"
      - "master-docker-nonstandard/master.cfg"
      - "master-galera/master.cfg"
      - "master-nonlatent/master.cfg"
      - "master-protected-branches/master.cfg"
      - "master-web/master.cfg"
      - "master.cfg"
      - "utils.py"
      - "validate_master_cfg.sh"
  pull_request:
    paths:
      - ".github/workflows/bbm_check_conf.yml"
      - "autogen/**"
      - "builtbot.tac"
      - "common_factories.py"
      - "constants.py"
      - "locks.py"
      - "master-docker-nonstandard/master.cfg"
      - "master-galera/master.cfg"
      - "master-nonlatent/master.cfg"
      - "master-protected-branches/master.cfg"
      - "master-web/master.cfg"
      - "master.cfg"
      - "utils.py"
      - "validate_master_cfg.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    name: check

    steps:
      - uses: actions/checkout@v2
      - name: Check master.cfg files
        run: ./validate_master_cfg.sh
